// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Blogs", testBlogs)
}

func TestDelete(t *testing.T) {
	t.Run("Blogs", testBlogsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Blogs", testBlogsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Blogs", testBlogsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Blogs", testBlogsExists)
}

func TestFind(t *testing.T) {
	t.Run("Blogs", testBlogsFind)
}

func TestBind(t *testing.T) {
	t.Run("Blogs", testBlogsBind)
}

func TestOne(t *testing.T) {
	t.Run("Blogs", testBlogsOne)
}

func TestAll(t *testing.T) {
	t.Run("Blogs", testBlogsAll)
}

func TestCount(t *testing.T) {
	t.Run("Blogs", testBlogsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Blogs", testBlogsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Blogs", testBlogsInsert)
	t.Run("Blogs", testBlogsInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("Blogs", testBlogsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Blogs", testBlogsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Blogs", testBlogsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Blogs", testBlogsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Blogs", testBlogsSliceUpdateAll)
}
